### ISSUE TITLE
Markdown Notation Error

### ISSUE THREAD

**Issue by jun-sforzando** [szk-engineering/loremipsum#3]
## Screenshots
<img width="1136" alt="Screen Shot 2020-08-05 at 17 54 47" src="https://user-images.githubusercontent.com/67792139/89392774-ef413f00-d744-11ea-84e0-6eadb24db9d3.png">

## Describe the bug

The notation in the markdown list is an asterisk.
## Expected behavior
I think `-` is better than `*`.
## To reproduce
none

## Additional context

none

**Comment by shin-sforzando** [comment]
> I think '-' is better than '*'.

正しくMarkdownを使うと、
I think `-` is better than `*` .
ですね。

**Comment by shin-sforzando** [comment]
> Desktop (please complete the following information)
> OS: [macOS 10.15.6]
> Browser: [chrome]
> Version: [84.0.4147.105]

`[]` は「例」という意味なので、書き換えた時には不要になります。
また、この不具合はMarkdownのもので、MacOSじゃなかろうと、Chromeじゃなかろうと発生すると思いますが、
そういう場合は再現環境は章ごと消しても良いです。

**Comment by jun-sforzando** [comment]
> ## Screenshots
> <img alt="Screen Shot 2020-08-05 at 17 54 47" width="1136" src="https://user-images.githubusercontent.com/67792139/89392774-ef413f00-d744-11ea-84e0-6eadb24db9d3.png">
> 
> ## Describe the bug
> The notation in the markdown list is an asterisk.
> 
> ## Expected behavior
> I think '-' is better than '*'.
> 
> ## To reproduce
> none
> 
> ### Desktop (please complete the following information)
> * OS: [macOS 10.15.6]
> * Browser: [chrome]
> * Version: [84.0.4147.105]
> 
> ## Additional context
> none
